(function(g){var window=this;var y4=function(a){var b={format:a.o,languageCode:a.l,languageName:a.C,displayName:g.fJ(a),kind:a.A,name:a.B,id:a.ia,is_servable:a.L,is_default:a.isDefault,is_translateable:a.F,vss_id:a.D};a.g&&(a=a.g,b.translationLanguage={languageCode:a.languageCode,languageName:a.languageName,languageOriginal:a.g,id:a.id,is_default:a.isDefault});return b},z4=function(a){return a.g?a.g.languageCode:a.l},Lza=function(a,b){var c=new g.eJ;
c.l=a.l;c.C=a.C;c.B=a.B;c.A=a.A;c.isDefault=!1;c.F=a.F;c.D=a.D;c.G=a.G;c.g=b;return c},Mza=function(a){a=g.rd(window.document,"track",void 0,a.g);
for(var b=0;b<a.length;b++)g.Ld(a[b])},A4=function(a){if(!Nza.test(a))throw Error("'"+a+"' is not a valid hex color");
4==a.length&&(a=a.replace(Oza,"#$1$1$2$2$3$3"));a=a.toLowerCase();return[(0,window.parseInt)(a.substr(1,2),16),(0,window.parseInt)(a.substr(3,2),16),(0,window.parseInt)(a.substr(5,2),16)]},B4=function(a,b,c,d,e,f,k){f=void 0===f?!1:f;
k=void 0===k?null:k;g.FQ.call(this,a,a+b,{priority:c,namespace:"captions"});this.windowId=d;this.text=e;this.C=f;this.l=k},C4=function(a,b,c,d,e){g.FQ.call(this,a,a+b,{priority:c,
namespace:"captions"});this.id=d;this.params=e;this.l=[]},E4=function(a){a=void 0===a?{}:a;
var b="_"+D4++;return new C4(0,0x8000000000000,0,b,a)},F4=function(a,b,c,d,e,f){var k={};
g.Ga(k,b);g.Ga(k,a.params);g.Ga(k,c);var l={};g.Ga(l,b.Za);a.params.Za&&g.Ga(l,a.params.Za);g.Ga(l,c.Za);k.Za=l;g.U.call(this,{H:"div",M:"caption-window",U:{id:"caption-window-"+a.id,dir:1==k.bk?"rtl":"ltr",tabindex:"0","aria-live":"assertive",lang:k.lang},J:[{H:"span",M:"captions-text"}]});this.B=[];this.L=!1;this.F=a;this.D=[];this.G=[];this.za=e;this.Ba=f;this.C=null;this.Y=.96*e;this.ga=.96*f;this.o=k;this.pa=c;this.A=this.g["captions-text"];this.la=null!=this.A.style["box-decoration-break"]||
null!=this.A.style["-webkit-box-decoration-break"];this.N=d/360*16;this.type=0;this.ca=this.N*Pza(l);a=new g.bG(this.element,!0);g.L(this,a);a.subscribe("dragstart",this.lN,this);a.subscribe("dragmove",this.kN,this);a.subscribe("dragend",this.jN,this);this.ea=this.da=0;a="";this.o.mk&&(a=A4(this.o.windowColor),a="rgba("+a[0]+","+a[1]+","+a[2]+","+this.o.mk+")");b={"background-color":a,display:!1===this.o.isVisible?"none":"","text-align":Qza[this.o.textAlign]};this.la&&(b["border-radius"]=a?this.ca/
8+"px":"");g.sh(this.element,b);switch(this.o.wf){case 0:case 1:case 2:g.Q(this.element,"ytp-caption-window-top");break;case 6:case 7:case 8:g.Q(this.element,"ytp-caption-window-bottom")}},Pza=function(a){var b=1+.25*(a.Zi||0);
if(0==a.offset||2==a.offset)b*=.8;return b},G4=function(a,b){var c={},d=b.background?b.background:a.o.Za.background;
if(null!=b.Ve||b.background){var e=null!=b.Ve?b.Ve:a.o.Za.Ve;d=A4(d);c.background="rgba("+d[0]+","+d[1]+","+d[2]+","+e+")";a.la&&(c["box-decoration-break"]="clone",c["border-radius"]=a.ca/8+"px")}if(null!=b.Zi||null!=b.offset)c["font-size"]=a.N*Pza(b)+"px";d=1;e=b.color||a.o.Za.color;if(b.color||null!=b.vh)e=A4(e),d=null==b.vh?a.o.Za.vh:b.vh,e="rgba("+e[0]+","+e[1]+","+e[2]+","+d+")",c.color=e,c.fill=e;var f=b.Lh;0==f&&(f=null);if(f){e="rgba(34, 34, 34, "+d+")";var k="rgba(204, 204, 204, "+d+")";
b.zw&&(k=e=b.zw);var l=a.N/16/2,m=Math.max(l,1),n=Math.max(2*l,1),q=Math.max(3*l,1),r=Math.max(5*l,1);d=[];switch(f){case 4:for(;q<=r;q+=l)d.push(n+"px "+n+"px "+q+"px "+e);break;case 1:n=2<=window.devicePixelRatio?.5:1;for(f=m;f<=q;f+=n)d.push(f+"px "+f+"px "+e);break;case 2:d.push(m+"px "+m+"px "+k);d.push("-"+m+"px -"+m+"px "+e);break;case 3:for(q=0;5>q;q++)d.push("0 0 "+n+"px "+e)}c["text-shadow"]=d.join(", ")}e="";switch(b.fontFamily){case 1:e='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';
break;case 2:e='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:e='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:e='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:e='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case 7:e=g.OE()?'"Carrois Gothic SC", sans-serif-smallcaps':'"Arial Unicode Ms", Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:e=
'"YouTube Noto", Roboto, "Arial Unicode Ms", Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}e&&(c["font-family"]=e);e=b.offset;null==e&&(e=a.o.Za.offset);switch(e){case 0:c["vertical-align"]="sub";break;case 2:c["vertical-align"]="super"}7==b.fontFamily&&(c["font-variant"]="small-caps");b.bold&&(c["font-weight"]="bold");b.gs&&(c["font-style"]="italic");b.underline&&(c["text-decoration"]="underline");b.vr&&(c.visibility="hidden");return c},Rza=function(a,b,c){a.L=a.L||!!c;
var d={};g.Ga(d,a.o.Za);g.Ga(d,c||b.l);g.Ga(d,a.pa.Za);c=a.D[0];if(c&&d.background==c.background&&d.Ve==c.Ve&&!!d.vr==!!c.vr&&d.Lh==c.Lh){var e;for(e=0;e<a.D.length;e++)if(g.bc(d,a.D[e])){var f=a.G[e];break}if(!f){e={};for(var k in d)d[k]!=c[k]&&(e[k]=d[k]);f=g.Fd("SPAN");g.sh(f,G4(a,e));a.G[0].appendChild(f);e=1}a.G.length=e;a.D.length=e}else a.G.length=0,a.D.length=0,f=g.Fd("SPAN"),g.sh(f,G4(a,d)),a.A.appendChild(f);a.C&&a.C.parentNode!=f&&(g.Ld(a.C),f.appendChild(a.C));c=(k=g.v(b.text))?b.text.split("\n"):
[b.text];for(e=0;e<c.length;e++){var l=c[e];if(0<e||0==a.B.length||!b.C){if(0<e||0!=a.B.length){var m=g.Fd("BR");f.appendChild(m)}f.appendChild(g.Gd("\u00a0"));a.C=g.Gd("\u00a0");f.appendChild(a.C)}l&&(m=a.C,m.parentNode&&m.parentNode.insertBefore(k?g.Gd(l):l,m))}a.D.push(d);a.G.push(f);a.B.push(b)},Sza=function(){},I4=function(){this.A=this.l=this.mode=this.o=0;
this.B=new H4(this);this.C=new H4(this);this.g=[];this.clear()},Uza=function(a,b,c){if(255==a&&255==b||!a&&!b)return{Em:a,
Fm:b,result:0};a=Tza[a];b=Tza[b];if(a&128){if(!(b&128)&&0!=c.g&&c.l==b)return{Em:a,Fm:b,result:1}}else if(b&128&&1<=a&&31>=a)return{Em:a,Fm:b,result:2};return{Em:a,Fm:b,result:3}},Wza=function(a,b,c,d){255==b&&255==c||!b&&!c?(45==++a.A&&a.reset(),a.B.g.clear(),a.C.g.clear()):(a.A=0,Vza(a.B,b,c,d))},Xza=function(a,b){a.g.sort(function(a,b){var c=a.time-b.time;
return 0==c?a.order-b.order:c});
for(var c=0;c<a.g.length;c++){var d=a.g[c];a.l=d.time;0==d.type?Wza(a,d.tw,d.uw,b):1==d.type&&a.o&496&&Vza(a.C,d.tw,d.uw,b)}a.g.length=0},J4=function(){this.g=0},K4=function(){this.l=this.o=this.g=0},L4=function(){this.timestamp=this.qe=0},M4=function(a){this.o=[];
for(var b=0;15>=b;b++){this.o[b]=[];for(var c=0;32>=c;c++)this.o[b][c]=new L4}this.g=this.l=this.row=0;this.style=new J4;this.B=a;this.A=0},N4=function(a,b){if(3==a.style.g){for(var c=0,d=0,e=a.B.l+0,f="",k="",l=e,m=1;15>=m;++m){for(var n=!1,q=d?d:1;32>=q;++q){var r=a.o[m][q];
if(0!=r.qe){0==c&&(c=m,d=q);n=String.fromCharCode(r.qe);var u=r.timestamp;u<e&&(e=u);r.timestamp=l;k&&(f+=k,k="");f+=n;n=!0}if((0==r.qe||32==q)&&n){k="\n";break}else if(d&&!n)break}if(c&&!n)break}f&&b.B(c,d,e,l,f)}else for(d=c=0,f=e=a.B.l+0,k=1;15>=k;++k)for(l="",m=1;32>=m;++m)if(q=a.o[k][m],r=q.qe,0!=r&&(0==c&&(c=k,d=m),n=String.fromCharCode(r),u=q.timestamp,u<=e&&(e=u),l+=n,q.reset()),32==m||0==r)l&&b.B(c,d,e,f,l),e=f,l="",d=c=0},bAa=function(a,b){switch(a){case 0:return Yza[(b&127)-32];
case 1:return Zza[b&15];case 2:return $za[b&31];case 3:return aAa[b&31]}return 0},O4=function(a){return a.o[a.row][a.l]},P4=function(a,b,c){2<=b&&1<a.l&&(--a.l,O4(a).qe=0);
var d=O4(a);d.timestamp=a.B.l+0;d.qe=bAa(b,c);32>a.l&&a.l++},cAa=function(a,b,c,d){for(var e=0;e<d;e++)for(var f=0;32>=f;f++)a.o[b+e][f].Vm(a.o[c+e][f])},Q4=function(a,b,c){for(var d=0;d<c;d++)for(var e=0;32>=e;e++)a.o[b+d][e].reset()},R4=function(a){a.row=0<a.g?a.g:1;
a.l=1;Q4(a,0,15)},S4=function(a){this.A=a;
this.B=0;this.style=new J4;this.C=new M4(a);this.D=new M4(a);this.F=new M4(a);this.l=this.C;this.o=this.D;this.g=this.l},T4=function(a,b,c){var d=a.l,e=!1;
switch(a.style.get()){case 4:if(0<d.g)break;case 1:case 2:N4(d,c),R4(a.l),R4(a.o),d.row=15,d.g=b,e=!0}a.style.set(3);a.g=d;a.g.style=a.style;a.A.mode=1<<d.A;e?d.l=1:d.g!=b&&(d.g>b?(N4(d,c),Q4(d,d.row-d.g,b)):d.row<b&&(b=d.g),d.g=b)},dAa=function(a){a.style.set(1);
a.g=a.o;a.g.g=0;a.g.style=a.style;a.A.mode=1<<a.g.A},eAa=function(a){a.style.set(4);
a.g=a.F;a.g.style=a.style;a.A.mode=1<<a.g.A},H4=function(a){this.l=a;
this.g=new K4;this.B=0;this.o=new S4(a);this.C=new S4(a);this.A=this.o},Vza=function(a,b,c,d){a.g.update();
b=Uza(b,c,a.g);switch(b.result){case 0:return;case 1:case 2:return}var e=b.Em;c=b.Fm;if(32<=e||!e)a.l.mode&a.l.o&&(b=e,b&128&&(b=127),c&128&&(c=127),a=a.A.g,b&96&&P4(a,0,b),c&96&&P4(a,0,c),0!=b&&0!=c&&3==a.style.g&&N4(a,d));else if(e&16)a:if(!a.g.matches(e,c)&&(b=a.g,b.o=e,b.l=c,b.g=2,b=e&8?a.C:a.o,a.A=b,a.l.mode=1<<(a.B<<2)+(b.B<<1)+(4==b.style.g?1:0),(a.l.mode|1<<(a.B<<2)+(b.B<<1)+(4!=b.style.g?1:0))&a.l.o))if(c&64){d=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(e&7)<<1|c>>5&1];a=c&16?4*((c&14)>>1):
0;c=b.g;switch(b.style.get()){case 4:d=c.row;break;case 3:if(d!=c.row){if(d<c.g&&(d=c.g,d==c.row))break;var f=1+c.row-c.g,k=1+d-c.g;cAa(c,k,f,c.g);b=f;e=c.g;k<f?(f=k+e-f,0<f&&(b+=f,e-=f)):(f=f+e-k,0<f&&(e-=f));Q4(c,b,e)}}c.row=d;c.l=a+1}else switch(e&7){case 1:switch(c&112){case 32:P4(b.g,0,32);break a;case 48:57==c?(b=b.g,O4(b).qe=0,32>b.l&&b.l++):P4(b.g,1,c&15)}break;case 2:c&32&&P4(b.g,2,c&31);break;case 3:c&32&&P4(b.g,3,c&31);break;case 4:case 5:if(32<=c&&47>=c)switch(c){case 32:dAa(b);break;
case 33:b=b.g;1<b.l&&(--b.l,O4(b).qe=0);break;case 36:b=b.g;d=O4(b);for(a=0;15>=a;a++)for(c=0;32>=c;c++)if(b.o[a][c]==d){for(;32>=c;c++)b.o[a][c].reset();break}break;case 37:T4(b,2,d);break;case 38:T4(b,3,d);break;case 39:T4(b,4,d);break;case 40:P4(b.g,0,32);break;case 41:b.style.set(2);b.g=b.l;b.g.g=0;b.g.style=b.style;b.A.mode=1<<b.g.A;break;case 42:d=b.F;d.g=15;d.style.set(4);R4(d);eAa(b);break;case 43:eAa(b);break;case 44:a=b.l;switch(b.style.get()){case 1:case 2:case 3:N4(a,d)}Q4(a,0,15);break;
case 45:b:{a=b.g;switch(b.style.get()){default:case 2:case 1:break b;case 4:if(15>a.row){++a.row;a.l=1;break b}case 3:}2>a.g&&(a.g=2,a.row<a.g&&(a.row=a.g));b=a.row-a.g+1;N4(a,d);cAa(a,b,b+1,a.g-1);Q4(a,a.row,1)}break;case 46:Q4(b.o,0,15);break;case 47:N4(b.l,d);d=b.o;a=b.A.l+0;for(c=1;15>=c;++c)for(e=1;32>=e;++e)d.o[c][e].timestamp=a;d=b.o;b.o=b.l;b.l=d;dAa(b)}break;case 7:switch(c){case 33:case 34:case 35:b=b.g,32<(b.l+=c&3)&&(b.l=32)}}},U4=function(){},V4=function(a){this.l=a;
this.g=null},gAa=function(a,b,c){var d=a.getAttribute("t");
d=d?(0,window.parseInt)(d,10):1E3*(0,window.parseFloat)(a.getAttribute("start")||0);var e=a.getAttribute("d");e=e?(0,window.parseFloat)(e):1E3*(0,window.parseFloat)(a.getAttribute("dur")||0);b=a.getAttribute("w")||b;var f=!!a.getAttribute("append"),k=f?6:5;a=g.gs("<html>"+(a.firstChild&&a.firstChild.nodeValue||"")+"</html>");fAa(d,e,k,b,f,a.firstChild,{},c)},fAa=function(a,b,c,d,e,f,k,l){switch(f.tagName){case "b":k.bold=!0;
break;case "i":k.gs=!0;break;case "u":k.underline=!0;break;case "font":var m=f.getAttribute("color");W4.test(m);k.color=m}for(m=0;m<f.childNodes.length;m++){var n=f.childNodes[m];if(3==n.nodeType)l.push(new B4(a,b,c,d,n.nodeValue,e||0<m,g.Yb(k)?void 0:k));else{var q={};g.Ga(q,k);fAa(a,b,c,d,e||0<m,n,q,l)}}},X4=function(){this.l={};
this.g=null},Y4=function(a){this.A={};
this.G={};this.I={};this.B="_"+D4++;this.C=a;this.F={};this.l=this.g=null;this.D=!0},Z4=function(a,b){var c=a.getAttribute(b);
if(null!=c)return(0,window.parseFloat)(c)},$4=function(a,b){var c=a.getAttribute(b);
if(null!=c)return"1"==c},a5=function(a,b){var c=Z4(a,b);
if(void 0!=c)return c},b5=function(a,b){var c=a.getAttribute(b);
if(null!=c)return W4.test(c),c},hAa=function(a,b){var c={},d=b.getAttribute("ws");
g.Ga(c,d?a.I[d]:a.C);d=a5(b,"mh");null!=d&&(c.As=d);d=a5(b,"ju");null!=d&&(c.textAlign=d);d=a5(b,"pd");null!=d&&(c.bk=d);d=b5(b,"wfc");null!=d&&(c.windowColor=d);d=Z4(b,"wfo");void 0!=d&&(c.mk=d/255);return c},iAa=function(a,b){var c={},d=b.getAttribute("wp");
d&&g.Ga(c,a.G[d]);d=a5(b,"ap");null!=d&&(c.wf=d);d=Z4(b,"cc");null!=d&&(c.tq=d);d=Z4(b,"ah");null!=d&&(c.fh=d);d=Z4(b,"rc");null!=d&&(c.Qo=d);d=Z4(b,"av");null!=d&&(c.yh=d);return c},jAa=function(a,b,c,d){var e={};
g.Ga(e,iAa(a,b));g.Ga(e,hAa(a,b));d?g.bc(e,a.C)?(d=a.B,e=a.C):d="_"+D4++:d=b.getAttribute("id")||"0";a=Z4(b,"t")+c;b=Z4(b,"d")||0x8000000000000;return new C4(a,b,0,d,e)},c5=function(a,b,c){this.D=c;
this.version=this.C=this.A=this.g=0;this.l=new window.DataView(a);this.o=[]},d5=function(a){var b=a.g;
a.g+=1;return a.l.getUint8(b)},e5=function(a){var b=a.g;
a.g+=4;return a.l.getUint32(b)},f5=function(a,b){this.l=a;
this.track="CC3"==b.C?4:0;this.g=new I4;this.g.o=1<<this.track},lAa=function(a){if(g.v(a))return!1;
a=new c5(a,8,0);return kAa(a)},kAa=function(a){if(!(a.g<a.l.byteLength)||1380139777!=e5(a))return!1;
a.version=d5(a);if(1<a.version)return!1;d5(a);d5(a);d5(a);return!0},mAa=function(){this.l=[];
this.g=[]},g5=function(a,b){return b?a.g.concat(a.l):a.g},h5=function(a,b){switch(b.A){case "asr":var c=a.l;
g.Ma(c,(0,g.z)(b.I,b))||c.push(b);break;default:c=a.g,g.Ma(c,(0,g.z)(b.I,b))||c.push(b)}},i5=function(){},nAa=function(a,b,c,d,e,f,k,l,m){switch(k.tagName){case "b":l.bold=!0;
break;case "i":l.gs=!0;break;case "u":l.underline=!0}for(var n=0;n<k.childNodes.length;n++){var q=k.childNodes[n];if(3==q.nodeType)q=new B4(b,c,d,e.id,q.nodeValue,f||0<n,g.Yb(l)?void 0:l),m.push(q),e.l.push(q);else{var r={};g.Ga(r,l);nAa(a,b,c,d,e,!0,q,r,m)}}},j5=function(a){var b=0;
a=g.la(a.split(":"));for(var c=a.next();!c.done;c=a.next())b=60*b+(0,window.parseFloat)(c.value);return 1E3*b},oAa=function(a,b,c,d){d=Object.assign({As:0},d);
return new C4(a,b,c,"_"+D4++,d)},k5=function(a){g.K.call(this);
this.Iy=!!a;this.l=new mAa;this.D=[];this.g=null},qAa=function(a){var b={};
if(a=z4(a))b.lang=a,pAa.test(a)&&(b.bk=1);return b},rAa=function(a,b,c,d,e){d=d||0;
e=e||0;if(!g.v(b)){var f=new window.DataView(b);1718909296==f.getUint32(4)&&(f=g.yJ(f,1835295092),b=b.slice(f.dataOffset,f.dataOffset+f.size),lAa(b)||(b=g.ge(new window.Uint8Array(b))))}if(g.v(b)){if("WEBVTT"==b.substring(0,6))return a.g||(a.g=new i5),a.g.o(b,d);b=g.gs(b);if(!b||!b.firstChild)return[];a.g||("timedtext"==b.firstChild.tagName?3==(0,window.parseInt)(b.firstChild.getAttribute("format"),10)?a.g=new Y4(qAa(c)):a.g=new X4:a.g=new V4(qAa(c)));return a.g.o(b,d)}try{if(lAa(b))return a.g||(a.g=
new f5(e,c)),a.g.o(b,d)}catch(k){g.cE(k)}return[]},l5=function(a){k5.call(this,a.Lm);
this.A=void 0;this.o=null;this.D=a.captionTranslationLanguages},m5=function(){this.gb=[]},n5=function(a,b,c,d,e,f){g.K.call(this);
this.K=a;this.A=b;this.C=new m5;this.g=null;this.G=d;this.L=f;this.l=this.o=null;this.F=c;this.D=e||!1;this.I=new g.ku(this.az,1E3,this);g.L(this,this.I);this.B=new g.XF(this);g.L(this,this.B);this.B.O(b,"seekto",this.iA);this.iA(b.getCurrentTime());this.az()},sAa=function(a,b){var c=a.g;
a.g=g.Ja(a.F.Sg(b).g);c!=a.g&&a.L&&a.L()},tAa=function(a,b){var c=g.PK(b,a.K,{}).Oa(),d={format:"RAW",
withCredentials:!0};a.D&&(d.responseType="arraybuffer");a.l=g.cF(c,d,3,100).then((0,g.z)(a.TR,a));a.o=b;c=a.C;d=a.o.g[0].ya;var e=g.fb(c.gb,d);0<=e||0>e&&1==(-e-1)%2||(e=-e-1,0<e&&1==d-c.gb[e-1]&&e<c.gb.length&&1==c.gb[e]-d?(g.Ua(c.gb,e),g.Ua(c.gb,e-1)):0<e&&1==d-c.gb[e-1]?c.gb[e-1]=d:e<c.gb.length&&1==c.gb[e]-d?c.gb[e]=d:(g.bb(c.gb,e,0,d),g.bb(c.gb,e+1,0,d)))},o5=function(a,b){k5.call(this);
this.o=a;this.A=b;this.B=null;this.C=!1},uAa=function(a,b){if(b in a.o.g)return a.o.g[b];
if(g.nL(a.o))for(var c in a.o.g){var d=a.o.g[c];if(g.AH(d.info.mimeType)&&("386"!=c||g.X(a.A).experiments.g("html5_manifestless_captions_fmt3")))return d}return null},vAa=function(a,b){return a.ua||g.X(b).za&&null!=a.na&&null!=a.na.g.rawcc},p5=function(a,b,c,d,e,f){F4.call(this,a,b,c,d,e,f);
this.type=1},q5=function(a,b,c,d,e,f){F4.call(this,a,b,c,d,e,f);
g.Q(this.element,"ytp-caption-window-rollup");this.type=2;this.K=this.R=0;this.W=this.I=window.NaN;this.oa=null;this.aa=new g.ku(this.XR,433,this);g.L(this,this.aa)},r5=function(a){if(!a.R){var b=g.Fd("SPAN");
g.sh(b,G4(a,a.o.Za));a.A.appendChild(b);b.appendChild(g.Gd("M"));var c=b.offsetHeight,d=g.Fd("BR");b.appendChild(d);b.appendChild(g.Gd("M"));a.R=b.offsetHeight-c;a.A.removeChild(b)}return a.R},wAa=function(a){if((0,window.isNaN)(a.I)){var b=a.o.tq;
if(b){var c=g.Fd("SPAN");g.Ud(c,"\u2013".repeat(b));g.sh(c,G4(a,a.o.Za));a.A.appendChild(c);a.I=c.offsetWidth;a.A.removeChild(c)}else a.I=0}return a.I},s5=function(a,b,c,d){k5.call(this,d);
c=c||g.wE(a).hl||"";c=c.split("_").join("-");this.B=g.yE(a,{hl:c});this.A=b;this.C={};this.o=null},v5=function(a){g.pV.call(this,a);
g.kH({YTP_CLICK_FOR_SETTINGS:"Click $GEAR_ICON for settings",YTP_SAMPLE_SUBTITLES:"Captions look like this"});this.A=g.X(a);this.o=a.getVideoData();this.oa=g.TU(a);this.K=a;var b=null,c=g.zD("yt-html5-player-modules::subtitlesModuleData");c&&(b=new g.iD(c));this.aa=b;this.C={Za:{}};this.F={Za:{}};this.N=[];this.R={};this.Y={};this.L=!1;this.pa="1"==this.o.hc.cc_auto_caps||"1"==this.A.Ib.cc_auto_caps;b="3"==this.A.o&&!!a.app.B&&!!a.app.B.g.textTracks;this.D=(c=this.A.experiments.g("web_player_native_controls_live_captions_fix"))?
b&&!this.o.ua:b;this.ga=c&&b&&this.o.ua;c=b=this.l=this.B=this.G=this.I=this.X=this.la=null;this.D||(b=new g.hu(this.CD,void 0,this),g.L(this,b),c=new g.ku(this.IT,2E3,this),g.L(this,c));this.da=b;this.ea=c;this.W=new g.XF(this);g.L(this,this.W);this.D||this.W.O(a,"resize",this.zu);this.W.O(a,"onPlaybackAudioChange",this.UO);this.W.O(a,"crn_captions",this.oL,this);this.W.O(a,"crx_captions",this.pL,this);t5(this,u5(this,"display-settings")||{})},xAa=function(a){if(1==a.A.Lg||1==a.o.Lg||"alwayson"==
g.zO(a.o,"yt:cc"))return!0;
if(2==a.A.Lg){var b=u5(a,"module-enabled");if(null!=b)return!!b}if(a.o.captionTracks.length)var c=a.g.getAudioTrack().lq;return"ON"==c||"on"==g.zO(a.o,"yt:cc")},w5=function(a,b){if(a.l&&(void 0===b||!b)||!a.o.captionTracks.length)return!1;
var c=a.g.getAudioTrack();return!!c.qn||"FORCED_ON"==c.lq},y5=function(a,b){if(a.B){var c=g5(a.B.l,b||a.pa);
if(a.G&&a.G.g)return a.G.g;for(var d=[a.o.Kg,a.A.Kg,g.zO(a.o,"yt:cc_default_lang")],e=0;e<d.length;e++)for(var f=0;f<c.length;f++)if(z4(c[f])==d[e])return c[f];return a.G&&a.G.Eq?a.G.Eq:(d=c.find(function(a){return a.isDefault}))?d:c[0]||x5(a)}return null},x5=function(a){return a.G&&a.G.qn},yAa=function(a,b){for(var c=a.K.app.B.g.textTracks,d=a.l.toString(),e=0;e<c.length;e++){var f=c[e];
f.id==d&&(b?"showing"!=f.mode&&(f.mode="showing"):"showing"==f.mode&&(f.mode="disabled"))}},A5=function(a,b,c,d){a.loaded&&a.unload();
null!=c&&(a.L=c,a.L&&z5(a,"module-enabled",!!b));a.l=b;w5(a)&&(a.l=x5(a));a.load(d)},zAa=function(a,b){var c=g.I_(a.oa,!0).height;
if(!c)return null;var d=a.oa.Ja();switch(null!=b.params.As?b.params.As:b.params.wU?2:1<b.l.length?1:0){case 1:return new p5(b,a.C,a.F,c,d.width,d.height);case 2:return new q5(b,a.C,a.F,c,d.width,d.height);default:return new F4(b,a.C,a.F,c,d.width,d.height)}},t5=function(a,b,c){var d=B5.Za;
a.C={};g.Ga(a.C,B5);a.C.Za={};g.Ga(a.C.Za,d);a.F={Za:{}};var e=b.backgroundOverride?a.F:a.C,f=b.background||d.background;W4.test(f);e.Za.background=f;e=b.colorOverride?a.F:a.C;f=b.color||d.color;W4.test(f);e.Za.color=f;e=b.windowColorOverride?a.F:a.C;f=b.windowColor||B5.windowColor;W4.test(f);e.windowColor=f;e=b.backgroundOpacityOverride?a.F:a.C;f=b.backgroundOpacity;null==f&&(f=d.Ve);e.Za.Ve=f;e=b.fontSizeIncrementOverride?a.F:a.C;f=b.fontSizeIncrement;null==f&&(f=d.Zi);e.Za.Zi=f;e=b.textOpacityOverride?
a.F:a.C;f=b.textOpacity;null==f&&(f=d.vh);e.Za.vh=f;e=b.windowOpacityOverride?a.F:a.C;f=b.windowOpacity;null==f&&(f=B5.mk);e.mk=f;e=b.charEdgeStyleOverride?a.F:a.C;f=b.charEdgeStyle;null==f&&(f=d.Lh);e.Za.Lh=f;e=b.fontFamilyOverride?a.F:a.C;f=b.fontFamily;null==f&&(f=d.fontFamily);e.Za.fontFamily=f;a.loaded&&a.zu();c&&z5(a,"display-settings",b)},BAa=function(a,b){if(b&&!a.I){var c=E4({bk:0,
lang:"en"});a.I=[c,new B4(c.start,c.end-c.start,0,c.id,g.T("YTP_SAMPLE_SUBTITLES"))];g.eV(a.g,a.I)}else!b&&a.I&&(AAa(a,a.I),a.I=null)},AAa=function(a,b){g.gV(a.g,b);
(0,g.B)(b,function(a){g.Wa(this.N,a)},a);
a.da.Mk()},CAa=function(a,b){return a&&g.v(a)&&W4.test(a)?a:b},DAa=function(a,b){return g.ua(a)&&!(0,window.isNaN)(a)?Math.max(0,Math.min(1,(0,window.parseFloat)(a))):b},FAa=function(a,b){if(a&&g.v(a)){var c=EAa.indexOf(a);
return-1!=c?c:b}return b},HAa=function(a,b){if(a&&g.v(a)){var c=GAa.indexOf(a);
return-1!=c?c:b}return b},IAa=function(a,b){return g.ua(a)&&!(0,window.isNaN)(a)?g.cd(a,-2,4):b},u5=function(a,b){if(!a.aa)return null;
try{var c=a.aa.get(b)}catch(d){a.aa.remove(b)}return c},z5=function(a,b,c){if(a.aa)try{a.aa.set(b,c)}catch(d){}};
g.iJ.prototype.zn=g.ca(2,function(a){return(a=this.Rh(a))?a.l:0});
g.dL.prototype.zn=g.ca(1,function(){return 0});
g.eJ.prototype.I=g.ca(0,function(a){return a?this.toString()==a.toString():!1});
var pAa=/^(ar|ckb|dv|he|iw|fa|nqo|ps|sd|ug|ur|yi|.*[-_](Arab|Hebr|Thaa|Nkoo|Tfng))(?!.*[-_](Latn|Cyrl)($|-|_))($|-|_)/i,Oza=/#(.)(.)(.)/,Nza=/^#(?:[0-9a-f]{3}){1,2}$/i,W4=/^#(?:[0-9a-f]{3}){1,2}$/i,GAa="default monoSerif propSerif monoSans propSans casual cursive smallCaps".split(" "),EAa=["none","raised","depressed","uniform","dropShadow"];var Qza=["left","right","center"];var B5={windowColor:"#080808",mk:0,textAlign:2,wf:7,fh:50,yh:100,Za:{background:"#080808",Ve:.75,Lh:0,color:"#fff",fontFamily:4,Zi:0,vh:1,offset:1}};g.p(B4,g.FQ);g.p(C4,g.FQ);var D4=0;g.p(F4,g.U);g.h=F4.prototype;g.h.lN=function(a,b){var c=g.Ih(this.element,this.element.parentElement);this.da=a-c.x;this.ea=b-c.y;g.Q(this.element,"ytp-dragging")};
g.h.kN=function(a,b){var c=g.Lh(this.element),d=a-this.da-.02*this.za,e=b-this.ea-.02*this.Ba,f=(d+c.width/2)/this.Y*3;f=Math.floor(g.cd(f,0,2));var k=(e+c.height/2)/this.ga*3;k=Math.floor(g.cd(k,0,2));var l=f+3*k;d=(d+f/2*c.width)/this.Y;d=100*g.cd(d,0,1);c=(e+k/2*c.height)/this.ga;c=100*g.cd(c,0,1);this.F.params.wf=l;this.F.params.yh=c;this.F.params.fh=d;this.o.wf=l;this.o.yh=c;this.o.fh=d;this.vC()};
g.h.jN=function(){g.Cq(this.element,"ytp-dragging")};
g.h.vC=function(){this.Ci(this.B)};
g.h.Rb=function(){return this.type};
g.h.Ci=function(a){var b=Math.min(this.Gx(),this.Y),c=this.Fx();g.sh(this.element,{top:0,left:0,right:"",bottom:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"96%","max-height":"96%",margin:"",transform:""});this.aq(a);a={transform:"",top:"",left:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"","max-height":""};var d=.96*this.o.fh+2,e=this.o.wf;switch(e){case 0:case 3:case 6:a.left=d+"%";break;case 1:case 4:case 7:a.left=d+"%";d=this.A.offsetWidth;b||d?(b=b||d+1,a.width=b+"px",a["margin-left"]=
b/-2+"px"):a.transform+=" translateX(-50%)";break;case 2:case 5:case 8:a.right=100-d+"%"}b=.96*this.o.yh+2;switch(e){case 0:case 1:case 2:a.top=b+"%";break;case 3:case 4:case 5:a.top=b+"%";(c=c||this.element.clientHeight)?(a.height=c+"px",a["margin-top"]=c/-2+"px"):a.transform+=" translateY(-50%)";break;case 6:case 7:case 8:a.bottom=100-b+"%"}g.sh(this.element,a)};
g.h.aq=function(a){var b;for(b=0;b<a.length&&a[b]==this.B[b];b++);if(this.L||this.B.length>b)b=0,this.L=!1,this.B=[],this.D=[],this.G=[],this.C=null,g.Jd(this.A);for(;b<a.length;b++)Rza(this,a[b])};
g.h.Gx=function(){return 0};
g.h.Fx=function(){return 0};Sza.prototype.B=function(){};I4.prototype.clear=function(){this.A=this.l=this.mode=0;this.g=[];this.reset()};
I4.prototype.reset=function(){this.mode=0;this.B.reset(0);this.C.reset(1)};
var Tza=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,
12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255];J4.prototype.set=function(a){this.g=a};
J4.prototype.get=function(){return this.g};
K4.prototype.clear=function(){this.g=0};
K4.prototype.update=function(){this.g=2==this.g?1:0};
K4.prototype.matches=function(a,b){return 0!=this.g&&a==this.o&&b==this.l};
L4.prototype.Vm=function(a){this.qe=a.qe;this.timestamp=a.timestamp};
L4.prototype.reset=function(){this.timestamp=this.qe=0};
M4.prototype.debugString=function(){for(var a="\n",b=1;15>=b;++b){for(var c=1;32>=c;++c){var d=this.o[b][c];a=0==d.qe?a+"_":a+String.fromCharCode(d.qe)}a+="\n"}return a};
M4.prototype.reset=function(a){for(var b=0;15>=b;b++)for(var c=0;32>=c;c++)this.o[b][c].reset();this.A=a;this.g=0;this.l=this.row=1};
var Yza=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],Zza=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],$za=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,199,200,202,203,235,
206,207,239,212,217,249,219,171,187],aAa=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499];S4.prototype.reset=function(a,b){this.B=b;this.style.set(2);this.l=this.C;this.o=this.D;this.g=this.l;var c=(a<<2)+(b<<1);this.C.reset(c);this.D.reset(c);this.F.reset((a<<2)+(b<<1)+1)};
H4.prototype.reset=function(a){this.B=a;this.g.clear();this.A=this.o;this.o.reset(a,0);this.C.reset(a,1)};U4.prototype.reset=function(){};g.p(V4,U4);V4.prototype.o=function(a){var b=[];this.g||(this.g=E4(this.l),b.push(this.g));a=g.la(a.firstChild.childNodes);for(var c=a.next();!c.done;c=a.next())gAa(c.value,this.g.id,b);return b};g.p(X4,U4);
X4.prototype.o=function(a){var b=[];this.g||(this.g=E4(),this.l[this.g.id]=this.g,b.push(this.g));for(a=a.firstChild.firstChild;a;){switch(a.tagName){case "window":var c=a,d=c.getAttribute("id");a:{var e=c,f=this.l[d];if(e.getAttribute("t")||e.getAttribute("start")){c=e.getAttribute("start")?1E3*(0,window.parseFloat)(e.getAttribute("start")):(0,window.parseInt)(e.getAttribute("t"),10);f&&(f.end>=c?f.end=c:f=null);switch(e.getAttribute("op")){case "kill":c=null;break a;case "define":f=null}f||(f=E4());
var k={};f&&(g.Ga(k,f.params),f=f.params.Za)&&(k.Za={},g.Ga(k.Za,f));e.getAttribute("rc")&&(k.Qo=(0,window.parseInt)(e.getAttribute("rc"),10));e.getAttribute("cc")&&(k.tq=(0,window.parseInt)(e.getAttribute("cc"),10));e.getAttribute("ap")&&(f=(0,window.parseInt)(e.getAttribute("ap"),10),k.wf=0>f||8<f?7:f);e.getAttribute("ah")&&(k.fh=(0,window.parseInt)(e.getAttribute("ah"),10));e.getAttribute("av")&&(k.yh=(0,window.parseInt)(e.getAttribute("av"),10));e.getAttribute("vs")&&(k.isVisible=!!e.getAttribute("vs"));
e.getAttribute("ju")&&(k.textAlign=(0,window.parseInt)(e.getAttribute("ju"),10));e.getAttribute("pd")&&(k.bk=1,0==(0,window.parseInt)(e.getAttribute("pd"),10)&&(k.bk=0));e.getAttribute("bc")&&(k.Za||(k.Za={}),k.Za.backgroundColor=e.getAttribute("bc"));e.getAttribute("bo")&&(k.Za||(k.Za={}),k.Za.Ve=(0,window.parseInt)(e.getAttribute("bo"),10)/100);e.getAttribute("fc")&&(k.Za||(k.Za={}),k.Za.color=e.getAttribute("fc"));e.getAttribute("sd")&&(k.wU=(0,window.parseInt)(e.getAttribute("sd"),10));f=(0,window.parseInt)(e.getAttribute("d"),
10)||1E3*(0,window.parseFloat)(e.getAttribute("dur"))||0x8000000000000;e=e.getAttribute("id")||"0";c=new C4(c,f,0,e,k)}else c=null}this.l[d]=c;b.push(c);break;case "text":for(d=[],gAa(a,this.g.id,d),d=g.la(d),c=d.next();!c.done;c=d.next())c=c.value,this.l[c.windowId]&&b.push(c)}a=a.nextSibling}return b};g.p(Y4,U4);Y4.prototype.reset=function(){this.F={};this.l=this.g=null;this.D=!0};
Y4.prototype.o=function(a,b){a.firstChild.getAttribute("format");b=b||0;Number.isFinite(b);for(var c,d,e=g.la(a.firstChild.childNodes),f=e.next();!f.done;f=e.next())if(f=f.value,1==f.nodeType)switch(f.tagName){case "head":c=f;break;case "body":d=f}if(c)for(c=g.la(c.childNodes),e=c.next();!e.done;e=c.next())if(e=e.value,1==e.nodeType)switch(e.tagName){case "pen":f=e.getAttribute("id");var k=this.A,l={},m=e.getAttribute("p");m&&g.Ga(l,this.A[m]);m=$4(e,"b");null!=m&&(l.bold=m);m=$4(e,"i");null!=m&&
(l.gs=m);m=$4(e,"u");null!=m&&(l.underline=m);m=a5(e,"et");null!=m&&(l.Lh=m);m=a5(e,"of");null!=m&&(l.offset=m);m=b5(e,"bc");null!=m&&(l.background=m);m=b5(e,"ec");null!=m&&(l.zw=m);m=b5(e,"fc");null!=m&&(l.color=m);m=a5(e,"fs");void 0!=m&&0!=m&&(l.fontFamily=m);m=Z4(e,"sz");void 0!=m&&(l.Zi=m/100-1);m=Z4(e,"bo");void 0!=m&&(l.Ve=m/255);e=Z4(e,"fo");void 0!=e&&(l.vh=e/255);k[f]=l;break;case "ws":f=e.getAttribute("id");this.I[f]=hAa(this,e);break;case "wp":f=e.getAttribute("id"),this.G[f]=iAa(this,
e)}if(d){c=b;e=[];d=g.la(d.childNodes);for(f=d.next();!f.done;f=d.next())if(f=f.value,1==f.nodeType)switch(f.tagName){case "w":this.g=jAa(this,f,c,!1);(f=this.F[this.g.id])&&f.end>this.g.start&&(f.end=this.g.start);this.F[this.g.id]=this.g;e.push(this.g);break;case "p":var n=c;k=[];l=f.getAttribute("w")||this.B;m=!!$4(f,"a");n=(Z4(f,"t")||0)+n;var q=Z4(f,"d")||5E3;m||(!this.D&&this.l&&this.l.windowId==l&&this.l.end>n&&(this.l.end=n),this.l&&"\n"==this.l.text&&(this.l.text=""));var r=m?6:5,u=this.A[f.getAttribute("p")],
D=f.childNodes;D.length&&(this.D=null!=f.getAttribute("d"));for(var I=0;I<D.length;I++){var S=D[I];0<I&&(m=!0);var Z=void 0;1==S.nodeType&&(Z=S);if(Z&&"s"==Z.tagName){var V=Z;S=n;Z=q;var Ea=l,pa=m,wc=r,xd=V.textContent?V.textContent:"",Va=this.A[V.getAttribute("p")];V=Z4(V,"t")||0;S=new B4(S+V,Z-V,wc,Ea,xd,pa,Va)}else S=new B4(n,q,r,l,S.textContent||"",m,u);k.push(S);this.l=S}if(0<k.length)for(k[0].windowId==this.B&&(this.g=jAa(this,f,c,!0),e.push(this.g)),f=g.la(k),k=f.next();!k.done;k=f.next())k=
k.value,k.windowId=this.g.id,this.g.l.push(k),e.push(k)}c=e}else c=[];return c};g.p(c5,Sza);c5.prototype.B=function(a,b,c,d,e){if(c<d){var f="_"+D4++;c=c/1E3-this.D;d=d/1E3-this.D;a=new C4(c,d-c,5,f,{textAlign:0,wf:0,fh:2.5*b,yh:5.33*a});e=new B4(c,d-c,5,f,e);this.o.push(a);this.o.push(e)}};
g.p(f5,U4);f5.prototype.o=function(a){a=new c5(a,a.byteLength,this.l);if(kAa(a)){for(;a.g<a.l.byteLength;)for(0==a.version?a.A=e5(a)*(1E3/45):1==a.version&&(a.A=4294967296*e5(a)+e5(a)),a.C=d5(a);0<a.C;a.C--){var b=d5(a),c=d5(a),d=d5(a);b&4&&(b&3)==this.track&&(0==this.track||1==this.track)&&(b=this.g,b.g.push({time:a.A,type:this.track,tw:c,uw:d,order:b.g.length}))}Xza(this.g,a);return a.o}return[]};
f5.prototype.reset=function(){this.g.clear()};g.p(i5,U4);
i5.prototype.o=function(a,b){for(var c=[],d=a.split(JAa),e=1;e<d.length;e++){var f=d[e],k=b;if(""!=f&&!KAa.test(f)){var l=C5.exec(f);if(l&&4<=l.length){var m=j5(l[1]),n=j5(l[2])-m;m+=k;var q=l[3];l={};q=g.la(q?q.split(" "):[]);for(var r=q.next();!r.done;r=q.next())if(r=r.value.split(":"),2==r.length){var u=r[1];switch(r[0]){case "line":u.endsWith("%")&&(l.wf=0,l.yh=Number.parseInt(u,10));break;case "position":l.wf=0;l.fh=Number.parseInt(u,10);break;case "align":switch(u){case "start":l.textAlign=0;
break;case "middle":l.textAlign=2;break;case "end":l.textAlign=1}}}f=f.substring(C5.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");r=l;l=f;f={};if(0>l.indexOf("<")&&0>l.indexOf("&"))k=oAa(m,n,5,r),m=new B4(m,n,5,k.id,l,!1,g.Yb(f)?void 0:f),c.push(k),c.push(m),k.l.push(m);else{q=l.split(LAa);1==q.length?(l=5,r=oAa(m,n,l,r)):(u=l=6,r=Object.assign({tq:32},r),r=new C4(m,n,u,"_"+D4++,r));c.push(r);u=m;for(var D=0;D<q.length;D++){var I=q[D];if(0==D%2){var S=g.gs("<html>"+I+"</html>");if(S.getElementsByTagName("parsererror").length){var Z=
S.createElement("span");Z.appendChild(S.createTextNode(I))}else Z=S.firstChild;nAa(this,u,n-(u-m),l,r,0<D,Z,f,c)}else u=j5(I)+k}}}C5.lastIndex=0}}return c};
var KAa=/^NOTE/,JAa=/(?:\r\n|\r|\n){2,}/,C5=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})(?:[\\t ]*)(.*)(?:\\r\\n|\\r|\\n)","gm"),LAa=/<((?:[\d]{2}:)?[\d]{2}:[\d]{2}\.[\d]{3})>/;g.p(k5,g.K);k5.prototype.trackCount=function(){return g5(this.l,!0).length};
k5.prototype.Fd=function(){this.g=null};
k5.prototype.V=function(){g.K.prototype.V.call(this);this.Fd()};
k5.prototype.eC=function(){return!1};g.p(l5,k5);g.h=l5.prototype;g.h.ts=function(a,b){var c=this.Kk(a),d=(0,g.z)(function(c){this.o=null;b(c.responseText,a)},this);
this.Fd();this.o=g.FE(c,{format:"RAW",onSuccess:d,withCredentials:!0})};
g.h.us=function(a,b,c,d){this.A=c;if(d)for(b=g.la(d.captionTracks),c=b.next();!c.done;c=b.next())h5(this.l,c.value);a()};
g.h.Kk=function(a){var b=a.Oa(),c={};if(this.A||a.o)c.fmt=this.A||"srv"+a.o;a.g&&(c.tlang=a.g.languageCode);return g.yE(b,c)};
g.h.Fd=function(){k5.prototype.Fd.call(this);this.o&&this.o.abort()};
g.h.V=function(){this.Fd();k5.prototype.V.call(this)};m5.prototype.contains=function(a){a=g.fb(this.gb,a);return 0<=a||0>a&&1==(-a-1)%2};
m5.prototype.length=function(){return this.gb.length/2};g.p(n5,g.K);g.h=n5.prototype;g.h.V=function(){g.K.prototype.V.call(this);this.l&&this.l.cancel()};
g.h.iA=function(a){var b=this;if(this.F.kc())var c=this.B.O(this.A,"progresssync",function(){b.F.index.Lb()&&(b.reset(),b.g=null,sAa(b,b.A.getCurrentTime()),b.B.Aa(c))});
else sAa(this,a)};
g.h.reset=function(){this.C=new m5;this.l&&(this.l.cancel(),this.l=null)};
g.h.az=function(){var a;if(a=null!==this.g)a=this.g,a=a.g.mi(a);!a||this.l||this.g&&30<this.g.startTime-this.A.getCurrentTime()||(a=this.g,a=a.g.jl(a),!g.X(this.A).experiments.g("disable_captions_unknown_requests")&&!a.g[0].duration)||(this.C.contains(a.g[0].ya)||tAa(this,a),this.g=g.Ja(a.g));this.I.start()};
g.h.TR=function(a){var b=!(this.D?a.response:a.responseText)||400<=a.status;if(!g.X(this.A).experiments.g("disable_captions_redirects_redux")){var c=g.iL(a);if(c){a=g.PK(this.o,this.K,{});b=this.o;g.LK(b.l,a,c);b.requestId=a.get("req_id");tAa(this,this.o);return}}b||null===this.G||(this.D?this.G(a.response,1E3*this.o.g[0].startTime):this.G(a.responseText,1E3*this.o.g[0].startTime));this.l=this.o=null};g.p(o5,k5);g.h=o5.prototype;g.h.ts=function(a,b){this.Fd();var c=uAa(this,a.l);if(c){var d=c.index.zn(c.index.Bf());g.X(this.A).experiments.g("html5_disable_caption_starttime")||(d-=c.index.Vd(c.index.Bf()));d*=1E3;var e=g.X(this.A).za;this.B=new n5(new g.uK,this.A,c,function(c,e){b(c,a,e,d)},e||g.xH(c.info),(0,g.z)(function(){e&&(this.B&&this.B.reset(),this.g&&this.g.reset(),this.C=!0)},this))}};
g.h.eC=function(){var a=this.C;this.C=!1;return a};
g.h.us=function(a){if(g.X(this.A).za)h5(this.l,new g.eJ({format:1,languageCode:"rawcc",languageName:"CC1",name:"",is_servable:!0,is_default:!0,is_translateable:!1})),h5(this.l,new g.eJ({format:1,languageCode:"rawcc",languageName:"CC3",name:"",is_servable:!0,is_default:!0,is_translateable:!1}));else for(var b in this.o.g){var c=this.o.g[b];if(g.AH(c.info.mimeType)&&"rawcc"!=b&&("386"!=b||g.X(this.A).experiments.g("html5_manifestless_captions_fmt3"))){var d="en",e="English",f=".en";if(c=c.info.captionTrack)d=
c.languageCode,e=c.displayName,f=c.vssId;h5(this.l,new g.eJ({format:1,languageCode:d,languageName:e,name:"",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:f}))}}a()};
g.h.Fd=function(){k5.prototype.Fd.call(this);this.B&&(this.B.dispose(),this.B=null)};
g.h.Kk=function(){return""};
g.h.V=function(){this.Fd();k5.prototype.V.call(this)};g.p(p5,F4);p5.prototype.aq=function(a){var b=this.F.l;F4.prototype.aq.call(this,a);for(a=a.length;a<b.length;a++){var c=b[a];if(f&&c.l==e)var d=f;else{d={};g.Ga(d,c.l);g.Ga(d,MAa);var e=c.l;var f=d}Rza(this,c,d)}};
var MAa={vr:!0};g.p(q5,F4);g.h=q5.prototype;g.h.vC=function(){g.mu(this.aa)};
g.h.XR=function(){g.Cq(this.element,"ytp-rollup-mode");this.Ci(this.oa,!0)};
g.h.Gx=function(){return this.K};
g.h.Fx=function(){return this.F.params.Qo*r5(this)};
g.h.Ci=function(a,b){this.oa=a;if(r5(this)){for(var c=0,d=0;d<this.B.length&&c<a.length;d++)this.B[d]==a[c]&&c++;0<c&&c<a.length&&(a=this.B.concat(a.slice(c)));c=this.K;this.K=0;F4.prototype.Ci.call(this,a);d=this.A.offsetWidth+1;this.K=Math.max(wAa(this),c,d);c=this.F.params.Qo*r5(this)-this.A.offsetHeight;c!=this.W&&(b||(0,window.isNaN)(this.W)||(g.Q(this.element,"ytp-rollup-mode"),g.lu(this.aa)),g.sh(this.A,"transform",c?"translateY("+c+"px)":""),this.W=c);F4.prototype.Ci.call(this,a)}else F4.prototype.Ci.call(this,
a)};g.p(s5,k5);g.h=s5.prototype;g.h.ts=function(a,b){var c=this.Kk(a),d=(0,g.z)(function(c){this.o=null;b(c.responseText,a)},this);
this.Fd();this.o=g.FE(c,{format:"RAW",onSuccess:d,withCredentials:!0})};
g.h.us=function(a,b,c){var d=this.B;b={type:"list",tlangs:1,v:this.A,fmts:Number(b||!1),vssids:1};this.Iy&&(b.asrs=1);d=g.yE(d,b);b=(0,g.z)(function(b){this.o=null;if((b=b.responseXML)&&b.firstChild){for(var d=this.l,e=g.la(b.getElementsByTagName("track")),l=e.next();!l.done;l=e.next()){var m=l.value;l=m.getAttribute("formats");var n=m.getAttribute("lang_code"),q=m.getAttribute("lang_translated"),r=m.getAttribute("name"),u=m.getAttribute("kind"),D=m.getAttribute("id"),I="true"==m.getAttribute("lang_default"),
S="true"==m.getAttribute("cantran");m=m.getAttribute("vss_id");h5(d,new g.eJ({formats:l,format:c,languageCode:n,languageName:q,name:r,kind:u,id:D,is_servable:!0,is_translateable:S,vss_id:m,is_default:I}))}b=b.getElementsByTagName("target");d=b.length;for(e=0;e<d;e++)l=b[e].getAttribute("lang_code"),n=b[e].getAttribute("lang_translated"),q=b[e].getAttribute("lang_original"),r=b[e].getAttribute("id"),u="true"==b[e].getAttribute("lang_default"),l={languageCode:l,languageName:n,languageOriginal:q,id:r,
is_default:u},this.C[l.languageCode]=l.languageName,this.D.push(new g.dJ(l))}a()},this);
this.Fd();this.o=g.FE(d,{format:"RAW",onSuccess:b,withCredentials:!0})};
g.h.Kk=function(a){var b=this.B,c={v:this.A,type:"track",lang:a.l,name:a.B,kind:a.A,fmt:a.o};a.g&&(c.tlang=z4(a));return b=g.yE(b,c)};
g.h.Fd=function(){k5.prototype.Fd.call(this);this.o&&this.o.abort()};
g.h.V=function(){this.Fd();k5.prototype.V.call(this)};g.p(v5,g.pV);g.h=v5.prototype;g.h.V=function(){if(this.D){var a=this.K.app.B;a&&Mza(a)}else BAa(this,!1);g.pV.prototype.V.call(this)};
g.h.Ez=function(){return this.D?!this.o.ua:this.ga||w5(this)?!0:xAa(this)};
g.h.load=function(a){g.pV.prototype.load.call(this);this.G=this.g.getAudioTrack();if(this.B||a)this.l&&(this.D&&!this.A.experiments.g("disable_native_caption_api")?yAa(this,!0):a?this.OB(a,this.l):3!=this.g.Pa()&&this.B.ts(this.l,(0,g.z)(this.OB,this))),this.l&&this.l!=x5(this)?this.g.ra("captionschanged",y4(this.l)):this.g.ra("onCaptionsTrackListChanged");else{var b;vAa(this.o,this.K)?b=new o5(this.o.na,this.g):this.o.captionTracks.length?b=new l5(this.o):b=new s5(this.o.Mm,this.o.videoId,this.o.Kg||
this.A.Kg||g.zO(this.o,"yt:cc_default_lang")||this.A.pa,this.o.Lm);this.B=b;b.us((0,g.z)(this.BS,this),!0,this.D?"vtt":void 0,this.g.getAudioTrack())}};
g.h.unload=function(){this.D?this.A.experiments.g("disable_native_caption_api")?Mza(this.K.app.B):this.l&&yAa(this,!1):(this.ea&&g.nu(this.ea),g.hV(this.g,"captions"),this.N=[],this.B&&this.B.Fd(),this.I&&g.eV(this.g,this.I),this.zu());g.pV.prototype.unload.call(this);var a=g.RU(this.g.app);a&&a.C&&g.SO(a.C.o);this.g.ra("captionschanged",{})};
g.h.BS=function(){var a;this.L||xAa(this)?a=y5(this,this.L):w5(this)&&(a=x5(this));if(this.D||this.ga){for(var b=g5(this.B.l,!0),c=[],d=0;d<b.length;d++){var e=b[d],f={kind:"subtitles",label:g.fJ(e),srclang:z4(e),id:e.toString()};this.ga||(f.src=this.B.Kk(e));e==a&&(f["default"]=1);c.push(g.J("TRACK",f))}a=this.K.app.B;for(b=0;b<c.length;b++)a.g.appendChild(c[b]);(c=this.K.app.B.g)&&c.textTracks&&c.textTracks.addEventListener&&!this.A.experiments.g("disable_native_caption_api")&&this.W.O(c.textTracks,
"change",this.CS)}else!this.l&&a&&A5(this,a),this.g.ra("onCaptionsTrackListChanged"),this.g.ra("onApiChange")};
g.h.CS=function(){for(var a=this.K.app.B.g.textTracks,b=null,c=0;c<a.length;c++)if("showing"==a[c].mode)a:{b=g5(this.B.l,!0);for(var d=0;d<b.length;d++)if(b[d].toString()==a[c].id){b=b[d];break a}b=null}(this.loaded?this.l:null)!=b&&A5(this,b,!0)};
g.h.KU=function(){this.A.experiments.g("disable_native_caption_api")?this.loaded&&!this.D&&this.unload():!this.l&&this.D||this.unload()};
g.h.OB=function(a,b,c,d){if(a){this.B.eC()&&(this.N=[],g.hV(this.K,"captions"),this.da.Mk());a=rAa(this.B,a,b,c,d);g.eV(this.g,a);if(this.L&&(a={trackName:b.B,trackKind:b.A,trackLangCode:z4(b)},b.g&&(a.fromLangCode=b.l),g.ZU(this.g,"cc",a),!this.ga&&this.l!=x5(this))){!this.L||g.GM(this.A)||g.NM(this.A)||(g.nu(this.ea),b=E4({wf:0,fh:5,yh:5,Qo:2,textAlign:0,bk:0,lang:"en"}),this.X=[b],a=g.T("YTP_CLICK_FOR_SETTINGS").split("$GEAR_ICON"),this.la||(c=new g.KI(g.wpa()),g.L(this,c),this.la=c.element),c=
b.end-b.start,(d=g.fJ(this.l))&&this.X.push(new B4(b.start,c,0,b.id,d)),this.X.push(new B4(b.start,c,0,b.id,a[0]),new B4(b.start,c,0,b.id,this.la,!0),new B4(b.start,c,0,b.id,a[1],!0)),g.eV(this.g,this.X),g.lu(this.ea));if(this.L||g.GM(this.A))z5(this,"module-enabled",!0),this.G&&(this.G.g=this.l);(b=g.RU(this.g.app))&&b.C&&g.SO(b.C.o)}this.L=!1}};
g.h.oL=function(a){this.N.push(a);this.da.Mk()};
g.h.pL=function(a){g.Wa(this.N,a);var b=vAa(this.o,this.K)&&this.A.za;!this.A.experiments.g("disable_remove_displayed_close_caption_cue")&&b&&g.gV(this.g,[a]);this.da.Mk()};
g.h.yT=function(a){if(a instanceof C4){var b=this.R[a.id];b&&b.F!=a&&(b.dispose(),delete this.R[a.id],b=null);b||(b=zAa(this,a))&&(this.R[a.id]=b)}else b=a.windowId,this.Y[b]||(this.Y[b]=[]),this.Y[b].push(a)};
g.h.IT=function(){AAa(this,this.X);this.X=null};
g.h.CD=function(){this.da.stop();g.Zb(this.Y);this.N.sort(g.HQ);var a=this.N;if(this.I){var b=(0,g.Md)(a,function(a){return-1==this.I.indexOf(a)},this);
b.length&&(a=b)}(0,g.B)(a,this.yT,this);g.Kb(this.R,function(a,b){this.Y[b]?(a.element.parentNode||g.jV(this.g,a.element,4),a.Ci(this.Y[b])):(a.dispose(),delete this.R[b])},this)};
g.h.uC=function(){t5(this,{},!0)};
g.h.Uq=function(){var a=B5.Za;a={background:a.background,backgroundOpacity:a.Ve,charEdgeStyle:a.Lh,color:a.color,fontFamily:a.fontFamily,fontSizeIncrement:a.Zi,textOpacity:a.vh,windowColor:B5.windowColor,windowOpacity:B5.mk};var b=u5(this,"display-settings"),c;for(c in b)null!=b[c]&&(a[c]=b[c]);return a};
g.h.Cu=function(a,b){var c={};g.Ga(c,u5(this,"display-settings"));g.Ga(c,a);t5(this,c,b);this.g.P("captionssettingschanged")};
g.h.zu=function(){!this.D&&this.loaded&&(g.Kb(this.R,function(a,b){a.dispose();delete this.R[b]},this),this.CD())};
g.h.Is=function(a,b){switch(a){case "fontSize":if((0,window.isNaN)(b))break;var c=g.cd(b,-2,4);this.Cu({fontSizeIncrement:c});return c;case "reload":b&&!this.D&&A5(this,this.l,!0);break;case "stickyLoading":void 0!=b&&this.A.Cb&&z5(this,"module-enabled",!!b);break;case "track":if(!this.B)return{};if(b){if(this.D)break;if(!g.Ba(b))break;if(g.Yb(b)){A5(this,null,!0);break}for(var d=g5(this.B.l,!0),e=0;e<d.length;e++){var f=d[e];f.l!=b.languageCode||c&&f.C!=b.languageName||(c=b.translationLanguage?Lza(f,
b.translationLanguage):f)}!c||c==this.l&&this.loaded||A5(this,c,!0)}else return this.loaded&&this.l&&this.l!=x5(this)?y4(this.l):{};return"";case "tracklist":return this.B?(0,g.G)(g5(this.B.l,!(!b||!b.includeAsr)),function(a){return y4(a)}):[];
case "translationLanguages":return this.B?this.B.D:[];case "displaySettings":c=this.Uq();if(g.GM(this.A)&&b&&g.Ba(b))if(b.reset)this.uC();else{f={};for(d in b)switch(d){case "color":case "background":case "windowColor":f[d]=CAa(b[d],c[d]);break;case "textOpacity":case "backgroundOpacity":case "windowOpacity":f[d]=DAa(b[d],c[d]);break;case "charEdgeStyle":f[d]=FAa(b[d],c[d]);break;case "fontSizeIncrement":f[d]=IAa(b[d],c[d]);break;case "fontFamilyOption":f.fontFamily=HAa(b[d],c[d])}for(e in f)f[e+
"Override"]=!0;this.Cu(f,!0);c=this.Uq()}c.fontFamilyOption=GAa[c.fontFamily];c.charEdgeStyle=EAa[c.charEdgeStyle];return c;case "sampleSubtitles":this.D||void 0==b||BAa(this,!!b);break;case "xmlTrack":b&&this.A.Cb&&(this.D||A5(this,new g.eJ({languageName:b.name}),!1,b.xml))}};
g.h.mL=function(){var a="reload fontSize track tracklist translationLanguages displaySettings sampleSubtitle".split(" ");this.A.Cb&&a.push("stickyLoading","xmlTrack");return a};
g.h.nL=function(){var a=this.l;return a?{cc:a.D}:{}};
g.h.rD=function(){this.loaded&&this.l&&this.l!=x5(this)?(z5(this,"module-enabled",!1),this.unload(),w5(this,!0)&&A5(this,x5(this),!1)):A5(this,this.l==x5(this)?y5(this,!0):this.l,!0)};
g.h.UO=function(){var a=this.l==x5(this);w5(this,a)?A5(this,this.g.getAudioTrack().qn,!1):this.o.captionTracks.length&&(this.loaded&&this.unload(),this.Ez()&&(a?A5(this,y5(this),!1):this.load()))};g.gY.captions=v5;})(_yt_player);
